# Generated by Django 4.2.7 on 2024-05-30 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCatalogue',
            fields=[
                ('library_catalogue_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('current_condition', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'library_catalogue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'resource_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('newspaper_id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_date', models.DateField()),
                ('source', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('library_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.librarycatalogue')),
            ],
            options={
                'db_table': 'newspaper',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='librarycatalogue',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.resourcetype'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('number_of_copies', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('library_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.librarycatalogue')),
            ],
            options={
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('content', models.TextField()),
                ('library_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.librarycatalogue')),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
    ]
