# Generated by Django 4.2.7 on 2024-05-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffrecords'),
        ('library_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingState',
            fields=[
                ('borrowing_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrowing_state', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'borrowing_states',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LendingBehaviour',
            fields=[
                ('lending_behaviour_id', models.AutoField(primary_key=True, serialize=False)),
                ('lending_behaviour', models.CharField(max_length=255)),
                ('occurrence', models.IntegerField()),
            ],
            options={
                'db_table': 'lending_behaviour',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LendingPreference',
            fields=[
                ('lending_preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('lending_preference', models.CharField(max_length=255)),
                ('occurrence', models.IntegerField()),
            ],
            options={
                'db_table': 'lending_preferences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MembershipStatus',
            fields=[
                ('membership_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('membership_status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'membership_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCatalogue',
            fields=[
                ('user_catalogue_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_lent', models.DateField()),
                ('date_returned', models.DateField()),
                ('duration_in_days', models.IntegerField()),
                ('borrow_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow_state', to='library_catalogue.borrowingstate')),
                ('library_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.librarycatalogue')),
                ('return_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_state', to='library_catalogue.borrowingstate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_catalogue',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_enrolled', models.DateField()),
                ('membership_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.membershipstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'membership',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberLendingPreference',
            fields=[
                ('member_lending_preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('lending_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.lendingpreference')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.membership')),
            ],
            options={
                'db_table': 'member_lending_preferences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberLendingBehaviour',
            fields=[
                ('member_lending_behaviour_id', models.AutoField(primary_key=True, serialize=False)),
                ('lending_behaviour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.lendingbehaviour')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.membership')),
            ],
            options={
                'db_table': 'member_lending_behaviour',
                'managed': True,
            },
        ),
    ]
