# Generated by Django 4.2.7 on 2024-06-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0002_borrowingstate_lendingbehaviour_lendingpreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingStatus',
            fields=[
                ('lending_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('lending_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lending_status',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usercatalogue',
            name='lending_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.lendingstatus'),
        ),
    ]
