# Generated by Django 4.2.7 on 2024-06-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0003_lendingstatus_usercatalogue_lending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='librarycatalogue',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_enrolled',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='publication_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usercatalogue',
            name='date_lent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
