# Generated by Django 4.2.7 on 2024-06-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0004_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
