# Generated by Django 4.2.7 on 2024-06-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0005_newspaper_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
