# Generated by Django 4.2.7 on 2024-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0006_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercatalogue',
            name='transaction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
