# Generated by Django 4.2.7 on 2024-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0007_usercatalogue_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercatalogue',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
