# Generated by Django 4.2.7 on 2024-06-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0008_alter_usercatalogue_date_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('format_id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'format',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'genres',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usercatalogue',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.format'),
        ),
        migrations.AddField(
            model_name='usercatalogue',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.genres'),
        ),
    ]
