# Generated by Django 4.2.7 on 2024-06-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0010_book_format_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
