# Generated by Django 4.2.7 on 2024-06-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0011_remove_book_format_remove_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycatalogue',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.format'),
        ),
        migrations.AddField(
            model_name='librarycatalogue',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_catalogue.genres'),
        ),
    ]
