# Generated by Django 4.2.7 on 2024-06-03 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0012_librarycatalogue_format_librarycatalogue_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercatalogue',
            name='format',
        ),
        migrations.RemoveField(
            model_name='usercatalogue',
            name='genre',
        ),
    ]
