# Generated by Django 4.2.7 on 2024-06-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_catalogue', '0013_remove_usercatalogue_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercatalogue',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
